return {
	ApiItem = require("@self/ApiItem"),
	ApiList = require("@self/ApiLIst"),
	ApiSignatureField = require("@self/ApiSignatureField"),
	Class = require("@self/Class"),
	Function = require("@self/Function"),
	FunctionParameter = require("@self/FunctionParameter"),
	FunctionReturn = require("@self/FunctionReturn"),
	Library = require("@self/Library"),
	Mechanic = require("@self/Mechanic"),
	Unimplemented = require("@self/Unimplemented"),
}
